wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 11
      2:
      - 1
      - 11
      3:
      - 1
      4: 3.7.10
      5: 0.10.20
      6: 4.3.2
      8:
      - 5
batch_size:
  desc: null
  value: 2
forward_batch_size:
  desc: null
  value: 2
model_name:
  desc: null
  value: lvwerra/gpt2-imdb
steps:
  desc: null
  value: 2
txt_in_max_len:
  desc: null
  value: 8
txt_in_min_len:
  desc: null
  value: 2
txt_out_max_len:
  desc: null
  value: 16
txt_out_min_len:
  desc: null
  value: 4
