wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.13.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1658005660
    t:
      1:
      - 1
      - 5
      - 11
      3:
      - 13
      - 16
      4: 3.9.7
      5: 0.12.7
      6: 4.13.0
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 1
forward_batch_size:
  desc: null
  value: 1
